name: "Build and Deploy GitHub Pages"
on:
  push:
    branches:
      - main
      - 26-schema-validate-cant-follow-yaml-anchors

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tooling
        run: |
          ./install-tooling.sh
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      - name: Build
        run: |
          ./build-openapi.sh
          echo "Copying built schema to interface/schemata"
          cp build/device.yaml interface/schemata/device.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          enable_jekyll: true
